[package]
name = "tg-tdjson"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde_json  = { workspace = true }
tracing     = { workspace = true }
dashmap     = { workspace = true }
uuid        = { workspace = true }
tokio       = { workspace = true }
anyhow      = { workspace = true }
libloading = "0.8"
